on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o audio
        run: |
          git clone -b main https://github.com/kayqueh/whisper-action.git ${{ github.workspace }}
          cd /home/runner/work/whisper-action/whisper-action/whisper
          pip install -U openai-whisper
          whisper whisper.mp3 --model medium
