on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparar ambiente
        run: |
          git clone -b main https://github.com/kayqueh/whisper-action.git ${{ github.workspace }}
          ls
