on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Run Whisper
      run: |
        git clone -b main https://github.com/kayqueh/whisper-action.git ${{ github.workspace }}
        cd /home/runner/work/whisper-action/whisper-action/
        sudo apt update
        sudo apt install ffmpeg -y
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -U openai-whisper

    - name: Run Whisper
      run: |
        whisper whisper.mp3
